### ISSUE TITLE
Stock glxgears won't start inside xorg-server 1.20

### ISSUE THREAD

**Issue by evanmiller** [kencu/TigerPorts#11]
The `xorg-server` update is looking great! Much more performant than 1.18, which I had to give up on.

Only snag that I've hit is that `/usr/X11R6/bin/glxgears` won't start:

```
$ /usr/X11R6/bin/glxgears
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  148 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  21
  Current serial number in output stream:  23
```

MacPorts glxgears works just fine. Not sure if this is fixable or worth addressing but wanted to let you know about it.

**Comment by kencu** [comment]
thanks. I guess there is not a great deal that can be done in the end, though.
