### ISSUE TITLE
[Question] SHA1SUM failure in Git

### ISSUE THREAD

**Issue by rickyzhang82** [kencu/TigerPorts#3]
I know that you didn't patch Git in your TigerPorts. But recently I did a port upgrade to 2.4.1 in Tiger.

I encountered several strange hash function error.

1. When upgrade axel, it complains compressed file checksum mismatch:
```
Error: Checksum (rmd160) mismatch for axel-2.13.1.tar.gz
Error: Checksum (sha256) mismatch for axel-2.13.1.tar.gz
Error: Failed to checksum axel: Unable to verify file checksums
Error: See /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_release_tarballs_ports_net_axel/axel/main.log for details.
Error: Follow https://guide.macports.org/#project.tickets to report a bug.
```
2. When use git to clone a repo, it complains SHA1 mismatch.

```
git clone --progress git://repo.or.cz/qgit4/redivivus.git
Cloning into 'redivivus'...
remote: Counting objects: 7471, done.
remote: Compressing objects: 100% (3028/3028), done.
remote: Total 7471 (delta 5767), reused 5653 (delta 4421)
Receiving objects: 100% (7471/7471), 1.93 MiB | 347.00 KiB/s, done.
fatal: pack is corrupted (SHA1 mismatch)
fatal: index-pack failed
```

I don't know what breaks macports hashing package. Any ideas?

**Comment by rickyzhang82** [comment]
So I dig it deeper. For No2, the issues only happens in recent git@ 2.14.1_1. If activate my old git @2.9.3_0, I can clone again.

```
Ricky@pg4:/tmp$ sudo port activate git
The following versions of git are currently installed:
 1) git @2.9.3_0+credential_osxkeychain+doc+pcre+perl5_22+python27
 2) git @2.14.1_1+credential_osxkeychain+doc+pcre+perl5_24 (active)
Enter a number to select an option: 1
--->  Deactivating git @2.14.1_1+credential_osxkeychain+doc+pcre+perl5_24
--->  Cleaning git
--->  Activating git @2.9.3_0+credential_osxkeychain+doc+pcre+perl5_22+python27

Ricky@pg4:/tmp$ git clone --progress git://repo.or.cz/qgit4/redivivus.git
Cloning into 'redivivus'...
remote: Counting objects: 7471, done.
remote: Compressing objects: 100% (3028/3028), done.
remote: Total 7471 (delta 5769), reused 5652 (delta 4421)
Receiving objects: 100% (7471/7471), 1.92 MiB | 386.00 KiB/s, done.
Resolving deltas: 100% (5769/5769), done.
Checking connectivity... done.
```

**Comment by rickyzhang82** [comment]
I believe the culprit is openssl package. But I haven't figured it out how to fix it.

**Comment by rickyzhang82** [comment]
I resolved he issue in axel. It is not related to openssl. But I still don't figure out git problem.

**Comment by kencu** [comment]
Hi Ricky, just noticed this. Yep, I had the same trouble - discussion on the open ticket on macports. Something strange, indeed. I found gcc6 builds it correctly, as a workaround.

**Comment by rickyzhang82** [comment]
Great. Do you have any trouble building gcc6 through macports?

**Comment by kencu** [comment]
gcc6 works great from MacPorts (and accepts -arch flag, which makes life **much** better)!  I use it for all c++11 builds. 

gcc7 is "confirmed" good on Leopard PPC (limited but successful testing so far), and so probably will be good on TigerPPC but haven't tried it yet. libgcc just switch to building from gcc7 instead of gcc6, so have to see if that builds now (it did up to now).

**Comment by rickyzhang82** [comment]
There is a showstopper that prevent me to build gcc6. Do you know how macports get the list of download URL. I don't see it specify in portfile. Neither MacPorts [documentation](https://guide.macports.org/chunked/reference.phases.html) explains it how it knows the URL.

Do you have any ideas?

```bash
Ricky@pg4:~$ sudo port install gcc6
--->  Computing dependencies for gcc6
The following dependencies will be installed: 
 isl
 libgcc
 libgcc6
 libmpc
 mpfr
Continue? [Y/n]: y
--->  Fetching distfiles for isl
--->  Attempting to fetch isl-0.18.tar.bz2 from http://distfiles.macports.org/isl
--->  Attempting to fetch isl-0.18.tar.bz2 from http://ykf.ca.distfiles.macports.org/MacPorts/mpdistfiles/isl
--->  Attempting to fetch isl-0.18.tar.bz2 from http://sea.us.distfiles.macports.org/macports/distfiles/isl
--->  Attempting to fetch isl-0.18.tar.bz2 from http://lil.fr.distfiles.macports.org/isl
--->  Attempting to fetch isl-0.18.tar.bz2 from http://mse.uk.distfiles.macports.org/sites/distfiles.macports.org/isl
--->  Attempting to fetch isl-0.18.tar.bz2 from http://isl.gforge.inria.fr
--->  Attempting to fetch isl-0.18.tar.bz2 from http://nue.de.distfiles.macports.org/isl
--->  Attempting to fetch isl-0.18.tar.bz2 from http://fco.it.distfiles.macports.org/mirrors/macports-distfiles/isl
--->  Attempting to fetch isl-0.18.tar.bz2 from http://osl.no.distfiles.macports.org/isl
--->  Attempting to fetch isl-0.18.tar.bz2 from http://cjj.kr.distfiles.macports.org/isl
--->  Attempting to fetch isl-0.18.tar.bz2 from http://aarnet.au.distfiles.macports.org/pub/macports/distfiles/isl
--->  Attempting to fetch isl-0.18.tar.bz2 from http://pek.cn.distfiles.macports.org/macports/distfiles/isl
--->  Attempting to fetch isl-0.18.tar.bz2 from http://jog.id.distfiles.macports.org/macports/distfiles/isl
--->  Attempting to fetch isl-0.18.tar.bz2 from http://nou.nc.distfiles.macports.org/pub/macports/distfiles.macports.org/isl
--->  Attempting to fetch isl-0.18.tar.bz2 from http://kmq.jp.distfiles.macports.org/isl
--->  Attempting to fetch isl-0.18.tar.bz2 from http://her.gr.distfiles.macports.org/isl
--->  Attempting to fetch isl-0.18.tar.bz2 from http://jnb.za.distfiles.macports.org/distfiles/isl
Error: Failed to fetch isl: The requested URL returned error: 404
```

**Comment by kencu** [comment]
Hey, that's strange. I have it, but it's no longer on the MacPorts mirrors, and the main site (inria.fr) seems to be down. Get it here for now <https://drive.google.com/open?id=0ByZ_RvKV76qzdGJSVmdRMTMyNXM>  and stick it here "/opt/local/var/macports/distfiles/isl/isl-0.18.tar.bz2" so MacPorts should find it.

**Comment by rickyzhang82** [comment]
Thanks for your file and hints! I get isl compiled now.

**Comment by rickyzhang82** [comment]
I got another error when run

```bash
port install gcc6
```

To my surprise, gcc6 depends on libgcc, which is gcc7 library. See [main.log.tar.gz](https://drive.google.com/file/d/0B0WAbKwAuXoPa3M1WlVONm1oV0E/view?usp=sharing)

Why gcc6 depends on libgcc7? In any case, do you encountered the issue?

**Comment by kencu** [comment]
That _just_ changed ; we have gcc7 working on 10.5 ppc with a patch(see macports tickets). 10.4 will probably work with same patch - not yet tested. You could be the guinea pig if you want! Otherwise, I'll need to roll back gcc6 in TigerPorts to theversion from a week ago. Can do that Tonight.

**Comment by rickyzhang82** [comment]
I wonder what gcc do you use to compile libgcc, which is gcc7 library.

**Comment by kencu** [comment]
the libgcc port is intertwined with a version of gcc. The gcc port provides the compilers and headers. The libgcc port provides all the backend libraries, libstdc++, etc. This was done so that one libgcc could service many gcc versions. It works well, but every once in a while, libgcc is moved to integrate with a new version of gcc. It was integrated with gcc6 for several years, but just changed to gcc7. 

I have pegged libgcc on TigerPorts at the last version, that was build at that time with gcc6. If you update your TigerPorts, and run a "sudo portindex", you should now find that libgcc is integrated with the gcc6 port (as it was last week), and not the gcc7 port (as it is now). In short, this should solve your troubles:>

I'll be testing the new libgcc that is integrated with gcc7 over the coming week on Tiger; it should work - it does on Leopard PPC, with patches. Once we have that confirmed, I'll be able to pull the libgcc peg, and we'll be back in sync with the rest of macports again!

Hope this is clear - it's a bit tricky.

**Comment by rickyzhang82** [comment]
Thanks for your detailed explanation. I'm building gcc6 now. It has been compiling for almost 12hrs since I started. I assume it will compile without errors soon.

When it is done, I want to confirm with you that the right way to specify gcc6 to build git:

```bash
sudo port upgrade git configure.compiler= (path to gcc6 binary)
```

**Comment by kencu** [comment]
You can force a compiler from the command line using the proper configure.compiler values specified here: <https://trac.macports.org/wiki/UsingTheRightCompiler>.

You do it like this from the command line:
```sudo port -v upgrade git configure.compiler=macports-gcc-6```

**Comment by rickyzhang82** [comment]
After 24 hours compiling, finally it solves git problem. I confirmed that 
1. Issue 1 is quite different from issue 2. It has been resolved in upstream.
1.using gcc6 solve mysterious git sha1 mismatch.

Thanks @kencu
