### ISSUE TITLE
"Tiger only" ports?

### ISSUE THREAD

**Issue by evanmiller** [kencu/TigerPorts#9]
I've been working on a couple of ports that only really make sense on pre-Lion systems. They are:

* `ppdc` - A collection of utilities for working with PPD (PostScript Printer Description) files, part of CUPS. These utilities are not included on Tiger, but are shipped with later versions of OS X. (Maybe Leopard, not sure?) See the [man page](https://www.cups.org/doc/man-ppdc.html)
* [`brlaser`](https://github.com/pdewacht/brlaser) - An open-source driver for monochrome Brother laser printers. For many newer Brother printers, the proprietary driver is only available for Lion and later. (Requires `ppdc` to build, hence the above.)

I'm somewhat hesitant to contribute either to MacPorts since they don't really make sense on systems from the last 10 years. I thought maybe TigerPorts would be a good home for them, but it looks like you're just shadowing existing ports right now.

Any interest in hosting these ports (or future ports like these)?

(And yes, printing to a brand-new Brother laser printer (well, refurbished) is possible from PowerPC :-)

**Comment by kencu** [comment]
I have to set up notifications from these repos -- I never seem to see these messages!

Sure, if there are Tiger-specific things that won't go into MacPorts we can put them here. I see these two did make it into MacPorts in the end, though.

**Comment by evanmiller** [comment]
Yep I decided to shop them upstream when I didn't hear back :-)  In the future I'll let you know if I have anything else that might be Tiger-specific but those were the only two I was sitting on.

**Comment by kencu** [comment]
I think I see the difference -- have to change the "watching" level to "All Activity" instead of the default to get notifications about issues and PRs where I am not specifically mentioned. Should work now.
